### ISSUE TITLE
Recieving UDP into Python?

### ISSUE THREAD

**Issue by jacksongoode** [bardiabarabadi/uvicMUSE#3]
Hi,

I've been testing your package out and was wondering if there was some easy instructions on how to receive the UDP packets into other platforms like Python instead of Matlab?

**Comment by jacksongoode** [comment]
I see that everything is being streamed over UDP port 1963, but I was wondering if you could give the schema for this data (which values are associated with which sensor?) I get a list of 24 values and it would be nice to split and assign them with osc /tags.

**Comment by bardiabarabadi** [comment]
Hello Jackson,

The data streams come into different UDP ports. Below are the offsets (for example, ACC come in 1963+2=1965)
EEG_OFFSET = 0;
PPG_OFFSET = 1;
ACC_OFFSET = 2;
GYRO_OFFSET = 3;

For each socket, the data comes in the form of an array of little-endian floating points. The last element of the array is the timestamp, and the rest contains the data for that sensor. However, the length of the data array is different for different sensors. For example, EEG has 5 data elements (in addition to TimeStamp), PPG has 3, etc.

See [this](https://github.com/bardiabarabadi/uvicMUSE/blob/c0c910314a21359d4e656bc13e0d70eaeb97bb83/uvicmuse/Backend.py#L211) 
Let me know if that does not answer your question. Otherwise, please go ahead and close the issue.

**Comment by jacksongoode** [comment]
Thank you, this would be nice to document on the readme so users can potentially grab these UDP streams for other purposes.
